name: Test

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        version: ['1.18', '1.19', '1.20']

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - name: Test
      run: go test -cover ./... -v

